approvedGitRepositories:
  - "**"

compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": ^25.5.2
      typescript: ^5.9.3
  "@module-federation/utilities@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "@patternfly/react-code-editor@*":
    peerDependencies:
      monaco-editor: ^0.52.0
  commitizen@*:
    peerDependencies:
      "@types/node": ^25.5.2
      typescript: ^5.9.3
  cz-conventional-changelog@*:
    peerDependencies:
      "@types/node": ^25.5.2
      typescript: ^5.9.3
  eslint-plugin-testing-library@*:
    peerDependencies:
      typescript: ^5.9.3

yarnPath: .yarn/releases/yarn-4.18.0.cjs
